version: "3.8"

services:
  postgres-db:
    image: postgres:9.6
    mem_limit: "6g"
    memswap_limit: "6g"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
